services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: credit-risk-api
    ports:
      - "8000:8000"
    volumes:
      - ./final_model:/code/final_model:ro
    restart: unless-stopped

  streamlit:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    container_name: credit-risk-ui
    ports:
      - "8501:8501"
    environment:
      - API_URL=http://api:8000
    depends_on:
      - api
    restart: unless-stopped
