columns:
- person_age: int64
- person_income: int64
- person_home_ownership: object
- person_emp_length: float64
- loan_intent: object
- loan_grade: object
- loan_amnt: int64
- loan_int_rate: float64
- loan_status: int64
- loan_percent_income: float64
- cb_person_default_on_file: boolean
- cb_person_cred_hist_length: int64

numerical_columns:
- person_age
- person_income
- person_emp_length
- loan_amnt
- loan_int_rate
- loan_status
- loan_percent_income
- cb_person_cred_hist_length
categorical_columns:
- person_home_ownership
- loan_intent
- loan_grade
boolean_columns:
- cb_person_default_on_file

data_cleansing:
  drop_duplicates: True
  missing_values:
    loan_int_rate:
      strategy: mean

  remove_values:
    person_emp_length:
      values:
        - 123
        - 124